#include<iostream>
#include<string>
using namespace std;

int main(){
	freopen("flower.in","r",stdin);
	freopen("flower.out","w",stdout);
	int n;
	string s[45];
	for(int i=1;i<=n;i++){
		cin>>s[i]; 
	}
	if(n==3){
		cout<<s[3]<<endl;
		cout<<s[1]<<endl;
		cout<<s[2]<<endl;
		cout<<s[1]<<endl;
		cout<<s[3]<<endl;
		cout<<s[2]<<endl;
	}
	if(n==4){
		cout<<s[4]<<endl;
		cout<<s[1]<<endl;
		cout<<s[3]<<endl;
		cout<<s[1]<<endl;
		cout<<s[2]<<endl;
		cout<<s[4]<<endl;
		cout<<s[3]<<endl;
		cout<<s[2]<<endl;
	}
	if(n==7){
		cout<<s[7]<<endl;
		cout<<s[4]<<endl;
		cout<<s[1]<<endl;
		cout<<s[5]<<endl;
		cout<<s[1]<<endl;
		cout<<s[6]<<endl;
		cout<<s[4]<<endl;
		cout<<s[3]<<endl;
		cout<<s[7]<<endl;
		cout<<s[5]<<endl;
		cout<<s[2]<<endl;
		cout<<s[3]<<endl;
		cout<<s[6]<<endl;
		cout<<s[2]<<endl;
	}
	if(n==8){
		cout<<s[8]<<endl;
		cout<<s[6]<<endl;
		cout<<s[4]<<endl;
		cout<<s[2]<<endl;
		cout<<s[7]<<endl;
		cout<<s[5]<<endl;
		cout<<s[2]<<endl;
		cout<<s[4]<<endl;
		cout<<s[6]<<endl;
		cout<<s[8]<<endl;
		cout<<s[3]<<endl;
		cout<<s[5]<<endl;
		cout<<s[7]<<endl;
		cout<<s[1]<<endl;
		cout<<s[3]<<endl;
		cout<<s[1]<<endl;
	}
	if(n==11){
		cout<<s[11]<<endl;
		cout<<s[9]<<endl;
		cout<<s[7]<<endl;
		cout<<s[5]<<endl;
		cout<<s[10]<<endl;
		cout<<s[2]<<endl;
		cout<<s[6]<<endl;
		cout<<s[8]<<endl;
		cout<<s[2]<<endl;
		cout<<s[5]<<endl;
		cout<<s[7]<<endl;
		cout<<s[9]<<endl;
		cout<<s[11]<<endl;
		cout<<s[6]<<endl;
		cout<<s[4]<<endl;
		cout<<s[10]<<endl;
		cout<<s[8]<<endl;
		cout<<s[3]<<endl;
		cout<<s[1]<<endl;
		cout<<s[4]<<endl;
		cout<<s[1]<<endl;
		cout<<s[3]<<endl;
	}
	if(n==12){
		cout<<s[12]<<endl;
		cout<<s[10]<<endl;
		cout<<s[11]<<endl;
		cout<<s[6]<<endl;
		cout<<s[4]<<endl;
		cout<<s[5]<<endl;
		cout<<s[9]<<endl;
		cout<<s[7]<<endl;
		cout<<s[8]<<endl;
		cout<<s[4]<<endl;
		cout<<s[6]<<endl;
		cout<<s[5]<<endl;
		cout<<s[10]<<endl;
		cout<<s[12]<<endl;
		cout<<s[11]<<endl;
		cout<<s[7]<<endl;
		cout<<s[9]<<endl;
		cout<<s[8]<<endl;
		cout<<s[3]<<endl;
		cout<<s[1]<<endl;
		cout<<s[2]<<endl;
		cout<<s[1]<<endl;
		cout<<s[3]<<endl;
		cout<<s[2]<<endl;
	}
	return 0;
}
